//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Scripts/Inputs/VRInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace VRInputs
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Inputs/VRInputActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @VRInputActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @VRInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""VRInputActions"",
    ""maps"": [
        {
            ""name"": ""LeftHandControls"",
            ""id"": ""a9cdcbdf-ee7d-4ac3-91b9-a463c1488360"",
            ""actions"": [
                {
                    ""name"": ""LeftGrip"",
                    ""type"": ""Button"",
                    ""id"": ""1f9faba3-04d1-461c-b453-500afd66f3b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""33abfa8b-576b-47dd-94d1-fc38741f7bdd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""c81b45ff-cfe0-49ff-8101-76915cd15233"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftSecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""336a13af-7698-40cb-a6b8-d5a371c6b763"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""63de6f2a-06e9-4715-995b-b888dbf83501"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f7470ab-e4a2-4c83-bd83-7161ae50012c"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f6d7c56-a4c9-4017-8276-366cd73a1ebd"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80c35e76-761f-4f3e-848c-1fceed5a3cda"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RightHandControls"",
            ""id"": ""d7846ea7-0c2c-4a47-b442-a0f1d2f65b23"",
            ""actions"": [
                {
                    ""name"": ""RightGrip"",
                    ""type"": ""Button"",
                    ""id"": ""6b3b6edc-ad0f-47f0-91f2-42e259509738"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""5f0b093f-934b-4667-8c6a-b8651d154edb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""b260c307-f19e-466c-b0f1-fea6e4221221"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""cb0b99b7-eceb-49fa-822e-77452e5a35f6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7e4ea2d8-1b58-4271-8b62-f1e055a96f85"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0eec620-a8e3-4559-963f-3d96477ad75a"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88337853-50bf-4525-a1b7-40ba346504c2"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccf93e35-8cf8-4608-a510-989cb5c1fda6"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New Control Scheme"",
            ""bindingGroup"": ""New Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // LeftHandControls
            m_LeftHandControls = asset.FindActionMap("LeftHandControls", throwIfNotFound: true);
            m_LeftHandControls_LeftGrip = m_LeftHandControls.FindAction("LeftGrip", throwIfNotFound: true);
            m_LeftHandControls_LeftTrigger = m_LeftHandControls.FindAction("LeftTrigger", throwIfNotFound: true);
            m_LeftHandControls_LeftPrimaryButton = m_LeftHandControls.FindAction("LeftPrimaryButton", throwIfNotFound: true);
            m_LeftHandControls_LeftSecondaryButton = m_LeftHandControls.FindAction("LeftSecondaryButton", throwIfNotFound: true);
            // RightHandControls
            m_RightHandControls = asset.FindActionMap("RightHandControls", throwIfNotFound: true);
            m_RightHandControls_RightGrip = m_RightHandControls.FindAction("RightGrip", throwIfNotFound: true);
            m_RightHandControls_RightTrigger = m_RightHandControls.FindAction("RightTrigger", throwIfNotFound: true);
            m_RightHandControls_RightPrimaryButton = m_RightHandControls.FindAction("RightPrimaryButton", throwIfNotFound: true);
            m_RightHandControls_RightSecondaryButton = m_RightHandControls.FindAction("RightSecondaryButton", throwIfNotFound: true);
        }

        ~@VRInputActions()
        {
            UnityEngine.Debug.Assert(!m_LeftHandControls.enabled, "This will cause a leak and performance issues, VRInputActions.LeftHandControls.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_RightHandControls.enabled, "This will cause a leak and performance issues, VRInputActions.RightHandControls.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // LeftHandControls
        private readonly InputActionMap m_LeftHandControls;
        private List<ILeftHandControlsActions> m_LeftHandControlsActionsCallbackInterfaces = new List<ILeftHandControlsActions>();
        private readonly InputAction m_LeftHandControls_LeftGrip;
        private readonly InputAction m_LeftHandControls_LeftTrigger;
        private readonly InputAction m_LeftHandControls_LeftPrimaryButton;
        private readonly InputAction m_LeftHandControls_LeftSecondaryButton;
        /// <summary>
        /// Provides access to input actions defined in input action map "LeftHandControls".
        /// </summary>
        public struct LeftHandControlsActions
        {
            private @VRInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public LeftHandControlsActions(@VRInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "LeftHandControls/LeftGrip".
            /// </summary>
            public InputAction @LeftGrip => m_Wrapper.m_LeftHandControls_LeftGrip;
            /// <summary>
            /// Provides access to the underlying input action "LeftHandControls/LeftTrigger".
            /// </summary>
            public InputAction @LeftTrigger => m_Wrapper.m_LeftHandControls_LeftTrigger;
            /// <summary>
            /// Provides access to the underlying input action "LeftHandControls/LeftPrimaryButton".
            /// </summary>
            public InputAction @LeftPrimaryButton => m_Wrapper.m_LeftHandControls_LeftPrimaryButton;
            /// <summary>
            /// Provides access to the underlying input action "LeftHandControls/LeftSecondaryButton".
            /// </summary>
            public InputAction @LeftSecondaryButton => m_Wrapper.m_LeftHandControls_LeftSecondaryButton;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_LeftHandControls; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="LeftHandControlsActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(LeftHandControlsActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="LeftHandControlsActions" />
            public void AddCallbacks(ILeftHandControlsActions instance)
            {
                if (instance == null || m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces.Add(instance);
                @LeftGrip.started += instance.OnLeftGrip;
                @LeftGrip.performed += instance.OnLeftGrip;
                @LeftGrip.canceled += instance.OnLeftGrip;
                @LeftTrigger.started += instance.OnLeftTrigger;
                @LeftTrigger.performed += instance.OnLeftTrigger;
                @LeftTrigger.canceled += instance.OnLeftTrigger;
                @LeftPrimaryButton.started += instance.OnLeftPrimaryButton;
                @LeftPrimaryButton.performed += instance.OnLeftPrimaryButton;
                @LeftPrimaryButton.canceled += instance.OnLeftPrimaryButton;
                @LeftSecondaryButton.started += instance.OnLeftSecondaryButton;
                @LeftSecondaryButton.performed += instance.OnLeftSecondaryButton;
                @LeftSecondaryButton.canceled += instance.OnLeftSecondaryButton;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="LeftHandControlsActions" />
            private void UnregisterCallbacks(ILeftHandControlsActions instance)
            {
                @LeftGrip.started -= instance.OnLeftGrip;
                @LeftGrip.performed -= instance.OnLeftGrip;
                @LeftGrip.canceled -= instance.OnLeftGrip;
                @LeftTrigger.started -= instance.OnLeftTrigger;
                @LeftTrigger.performed -= instance.OnLeftTrigger;
                @LeftTrigger.canceled -= instance.OnLeftTrigger;
                @LeftPrimaryButton.started -= instance.OnLeftPrimaryButton;
                @LeftPrimaryButton.performed -= instance.OnLeftPrimaryButton;
                @LeftPrimaryButton.canceled -= instance.OnLeftPrimaryButton;
                @LeftSecondaryButton.started -= instance.OnLeftSecondaryButton;
                @LeftSecondaryButton.performed -= instance.OnLeftSecondaryButton;
                @LeftSecondaryButton.canceled -= instance.OnLeftSecondaryButton;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="LeftHandControlsActions.UnregisterCallbacks(ILeftHandControlsActions)" />.
            /// </summary>
            /// <seealso cref="LeftHandControlsActions.UnregisterCallbacks(ILeftHandControlsActions)" />
            public void RemoveCallbacks(ILeftHandControlsActions instance)
            {
                if (m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="LeftHandControlsActions.AddCallbacks(ILeftHandControlsActions)" />
            /// <seealso cref="LeftHandControlsActions.RemoveCallbacks(ILeftHandControlsActions)" />
            /// <seealso cref="LeftHandControlsActions.UnregisterCallbacks(ILeftHandControlsActions)" />
            public void SetCallbacks(ILeftHandControlsActions instance)
            {
                foreach (var item in m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="LeftHandControlsActions" /> instance referencing this action map.
        /// </summary>
        public LeftHandControlsActions @LeftHandControls => new LeftHandControlsActions(this);

        // RightHandControls
        private readonly InputActionMap m_RightHandControls;
        private List<IRightHandControlsActions> m_RightHandControlsActionsCallbackInterfaces = new List<IRightHandControlsActions>();
        private readonly InputAction m_RightHandControls_RightGrip;
        private readonly InputAction m_RightHandControls_RightTrigger;
        private readonly InputAction m_RightHandControls_RightPrimaryButton;
        private readonly InputAction m_RightHandControls_RightSecondaryButton;
        /// <summary>
        /// Provides access to input actions defined in input action map "RightHandControls".
        /// </summary>
        public struct RightHandControlsActions
        {
            private @VRInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public RightHandControlsActions(@VRInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "RightHandControls/RightGrip".
            /// </summary>
            public InputAction @RightGrip => m_Wrapper.m_RightHandControls_RightGrip;
            /// <summary>
            /// Provides access to the underlying input action "RightHandControls/RightTrigger".
            /// </summary>
            public InputAction @RightTrigger => m_Wrapper.m_RightHandControls_RightTrigger;
            /// <summary>
            /// Provides access to the underlying input action "RightHandControls/RightPrimaryButton".
            /// </summary>
            public InputAction @RightPrimaryButton => m_Wrapper.m_RightHandControls_RightPrimaryButton;
            /// <summary>
            /// Provides access to the underlying input action "RightHandControls/RightSecondaryButton".
            /// </summary>
            public InputAction @RightSecondaryButton => m_Wrapper.m_RightHandControls_RightSecondaryButton;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_RightHandControls; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="RightHandControlsActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(RightHandControlsActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="RightHandControlsActions" />
            public void AddCallbacks(IRightHandControlsActions instance)
            {
                if (instance == null || m_Wrapper.m_RightHandControlsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_RightHandControlsActionsCallbackInterfaces.Add(instance);
                @RightGrip.started += instance.OnRightGrip;
                @RightGrip.performed += instance.OnRightGrip;
                @RightGrip.canceled += instance.OnRightGrip;
                @RightTrigger.started += instance.OnRightTrigger;
                @RightTrigger.performed += instance.OnRightTrigger;
                @RightTrigger.canceled += instance.OnRightTrigger;
                @RightPrimaryButton.started += instance.OnRightPrimaryButton;
                @RightPrimaryButton.performed += instance.OnRightPrimaryButton;
                @RightPrimaryButton.canceled += instance.OnRightPrimaryButton;
                @RightSecondaryButton.started += instance.OnRightSecondaryButton;
                @RightSecondaryButton.performed += instance.OnRightSecondaryButton;
                @RightSecondaryButton.canceled += instance.OnRightSecondaryButton;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="RightHandControlsActions" />
            private void UnregisterCallbacks(IRightHandControlsActions instance)
            {
                @RightGrip.started -= instance.OnRightGrip;
                @RightGrip.performed -= instance.OnRightGrip;
                @RightGrip.canceled -= instance.OnRightGrip;
                @RightTrigger.started -= instance.OnRightTrigger;
                @RightTrigger.performed -= instance.OnRightTrigger;
                @RightTrigger.canceled -= instance.OnRightTrigger;
                @RightPrimaryButton.started -= instance.OnRightPrimaryButton;
                @RightPrimaryButton.performed -= instance.OnRightPrimaryButton;
                @RightPrimaryButton.canceled -= instance.OnRightPrimaryButton;
                @RightSecondaryButton.started -= instance.OnRightSecondaryButton;
                @RightSecondaryButton.performed -= instance.OnRightSecondaryButton;
                @RightSecondaryButton.canceled -= instance.OnRightSecondaryButton;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="RightHandControlsActions.UnregisterCallbacks(IRightHandControlsActions)" />.
            /// </summary>
            /// <seealso cref="RightHandControlsActions.UnregisterCallbacks(IRightHandControlsActions)" />
            public void RemoveCallbacks(IRightHandControlsActions instance)
            {
                if (m_Wrapper.m_RightHandControlsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="RightHandControlsActions.AddCallbacks(IRightHandControlsActions)" />
            /// <seealso cref="RightHandControlsActions.RemoveCallbacks(IRightHandControlsActions)" />
            /// <seealso cref="RightHandControlsActions.UnregisterCallbacks(IRightHandControlsActions)" />
            public void SetCallbacks(IRightHandControlsActions instance)
            {
                foreach (var item in m_Wrapper.m_RightHandControlsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_RightHandControlsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="RightHandControlsActions" /> instance referencing this action map.
        /// </summary>
        public RightHandControlsActions @RightHandControls => new RightHandControlsActions(this);
        private int m_NewControlSchemeSchemeIndex = -1;
        /// <summary>
        /// Provides access to the input control scheme.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
        public InputControlScheme NewControlSchemeScheme
        {
            get
            {
                if (m_NewControlSchemeSchemeIndex == -1) m_NewControlSchemeSchemeIndex = asset.FindControlSchemeIndex("New Control Scheme");
                return asset.controlSchemes[m_NewControlSchemeSchemeIndex];
            }
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "LeftHandControls" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="LeftHandControlsActions.AddCallbacks(ILeftHandControlsActions)" />
        /// <seealso cref="LeftHandControlsActions.RemoveCallbacks(ILeftHandControlsActions)" />
        public interface ILeftHandControlsActions
        {
            /// <summary>
            /// Method invoked when associated input action "LeftGrip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftGrip(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LeftTrigger" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftTrigger(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LeftPrimaryButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftPrimaryButton(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LeftSecondaryButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftSecondaryButton(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "RightHandControls" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="RightHandControlsActions.AddCallbacks(IRightHandControlsActions)" />
        /// <seealso cref="RightHandControlsActions.RemoveCallbacks(IRightHandControlsActions)" />
        public interface IRightHandControlsActions
        {
            /// <summary>
            /// Method invoked when associated input action "RightGrip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightGrip(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightTrigger" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightTrigger(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightPrimaryButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightPrimaryButton(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightSecondaryButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightSecondaryButton(InputAction.CallbackContext context);
        }
    }
}
