//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.1
//     from Assets/Scripts/Inputs/VRInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

namespace VRInputs
{
    public partial class @VRInputActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @VRInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""VRInputActions"",
    ""maps"": [
        {
            ""name"": ""LeftHandControls"",
            ""id"": ""a9cdcbdf-ee7d-4ac3-91b9-a463c1488360"",
            ""actions"": [
                {
                    ""name"": ""LeftGrip"",
                    ""type"": ""Button"",
                    ""id"": ""1f9faba3-04d1-461c-b453-500afd66f3b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""33abfa8b-576b-47dd-94d1-fc38741f7bdd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""c81b45ff-cfe0-49ff-8101-76915cd15233"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftSecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""336a13af-7698-40cb-a6b8-d5a371c6b763"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""63de6f2a-06e9-4715-995b-b888dbf83501"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f7470ab-e4a2-4c83-bd83-7161ae50012c"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f6d7c56-a4c9-4017-8276-366cd73a1ebd"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80c35e76-761f-4f3e-848c-1fceed5a3cda"",
                    ""path"": ""<XRController>{LeftHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RightHandControls"",
            ""id"": ""d7846ea7-0c2c-4a47-b442-a0f1d2f65b23"",
            ""actions"": [
                {
                    ""name"": ""RightGrip"",
                    ""type"": ""Button"",
                    ""id"": ""6b3b6edc-ad0f-47f0-91f2-42e259509738"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""5f0b093f-934b-4667-8c6a-b8651d154edb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""b260c307-f19e-466c-b0f1-fea6e4221221"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""cb0b99b7-eceb-49fa-822e-77452e5a35f6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7e4ea2d8-1b58-4271-8b62-f1e055a96f85"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0eec620-a8e3-4559-963f-3d96477ad75a"",
                    ""path"": ""<XRController>{RightHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88337853-50bf-4525-a1b7-40ba346504c2"",
                    ""path"": ""<XRController>{RightHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccf93e35-8cf8-4608-a510-989cb5c1fda6"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // LeftHandControls
            m_LeftHandControls = asset.FindActionMap("LeftHandControls", throwIfNotFound: true);
            m_LeftHandControls_LeftGrip = m_LeftHandControls.FindAction("LeftGrip", throwIfNotFound: true);
            m_LeftHandControls_LeftTrigger = m_LeftHandControls.FindAction("LeftTrigger", throwIfNotFound: true);
            m_LeftHandControls_LeftPrimaryButton = m_LeftHandControls.FindAction("LeftPrimaryButton", throwIfNotFound: true);
            m_LeftHandControls_LeftSecondaryButton = m_LeftHandControls.FindAction("LeftSecondaryButton", throwIfNotFound: true);
            // RightHandControls
            m_RightHandControls = asset.FindActionMap("RightHandControls", throwIfNotFound: true);
            m_RightHandControls_RightGrip = m_RightHandControls.FindAction("RightGrip", throwIfNotFound: true);
            m_RightHandControls_RightTrigger = m_RightHandControls.FindAction("RightTrigger", throwIfNotFound: true);
            m_RightHandControls_RightPrimaryButton = m_RightHandControls.FindAction("RightPrimaryButton", throwIfNotFound: true);
            m_RightHandControls_RightSecondaryButton = m_RightHandControls.FindAction("RightSecondaryButton", throwIfNotFound: true);
        }

        ~@VRInputActions()
        {
            Debug.Assert(!m_LeftHandControls.enabled, "This will cause a leak and performance issues, VRInputActions.LeftHandControls.Disable() has not been called.");
            Debug.Assert(!m_RightHandControls.enabled, "This will cause a leak and performance issues, VRInputActions.RightHandControls.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // LeftHandControls
        private readonly InputActionMap m_LeftHandControls;
        private List<ILeftHandControlsActions> m_LeftHandControlsActionsCallbackInterfaces = new List<ILeftHandControlsActions>();
        private readonly InputAction m_LeftHandControls_LeftGrip;
        private readonly InputAction m_LeftHandControls_LeftTrigger;
        private readonly InputAction m_LeftHandControls_LeftPrimaryButton;
        private readonly InputAction m_LeftHandControls_LeftSecondaryButton;
        public struct LeftHandControlsActions
        {
            private @VRInputActions m_Wrapper;
            public LeftHandControlsActions(@VRInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @LeftGrip => m_Wrapper.m_LeftHandControls_LeftGrip;
            public InputAction @LeftTrigger => m_Wrapper.m_LeftHandControls_LeftTrigger;
            public InputAction @LeftPrimaryButton => m_Wrapper.m_LeftHandControls_LeftPrimaryButton;
            public InputAction @LeftSecondaryButton => m_Wrapper.m_LeftHandControls_LeftSecondaryButton;
            public InputActionMap Get() { return m_Wrapper.m_LeftHandControls; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LeftHandControlsActions set) { return set.Get(); }
            public void AddCallbacks(ILeftHandControlsActions instance)
            {
                if (instance == null || m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces.Add(instance);
                @LeftGrip.started += instance.OnLeftGrip;
                @LeftGrip.performed += instance.OnLeftGrip;
                @LeftGrip.canceled += instance.OnLeftGrip;
                @LeftTrigger.started += instance.OnLeftTrigger;
                @LeftTrigger.performed += instance.OnLeftTrigger;
                @LeftTrigger.canceled += instance.OnLeftTrigger;
                @LeftPrimaryButton.started += instance.OnLeftPrimaryButton;
                @LeftPrimaryButton.performed += instance.OnLeftPrimaryButton;
                @LeftPrimaryButton.canceled += instance.OnLeftPrimaryButton;
                @LeftSecondaryButton.started += instance.OnLeftSecondaryButton;
                @LeftSecondaryButton.performed += instance.OnLeftSecondaryButton;
                @LeftSecondaryButton.canceled += instance.OnLeftSecondaryButton;
            }

            private void UnregisterCallbacks(ILeftHandControlsActions instance)
            {
                @LeftGrip.started -= instance.OnLeftGrip;
                @LeftGrip.performed -= instance.OnLeftGrip;
                @LeftGrip.canceled -= instance.OnLeftGrip;
                @LeftTrigger.started -= instance.OnLeftTrigger;
                @LeftTrigger.performed -= instance.OnLeftTrigger;
                @LeftTrigger.canceled -= instance.OnLeftTrigger;
                @LeftPrimaryButton.started -= instance.OnLeftPrimaryButton;
                @LeftPrimaryButton.performed -= instance.OnLeftPrimaryButton;
                @LeftPrimaryButton.canceled -= instance.OnLeftPrimaryButton;
                @LeftSecondaryButton.started -= instance.OnLeftSecondaryButton;
                @LeftSecondaryButton.performed -= instance.OnLeftSecondaryButton;
                @LeftSecondaryButton.canceled -= instance.OnLeftSecondaryButton;
            }

            public void RemoveCallbacks(ILeftHandControlsActions instance)
            {
                if (m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ILeftHandControlsActions instance)
            {
                foreach (var item in m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_LeftHandControlsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public LeftHandControlsActions @LeftHandControls => new LeftHandControlsActions(this);

        // RightHandControls
        private readonly InputActionMap m_RightHandControls;
        private List<IRightHandControlsActions> m_RightHandControlsActionsCallbackInterfaces = new List<IRightHandControlsActions>();
        private readonly InputAction m_RightHandControls_RightGrip;
        private readonly InputAction m_RightHandControls_RightTrigger;
        private readonly InputAction m_RightHandControls_RightPrimaryButton;
        private readonly InputAction m_RightHandControls_RightSecondaryButton;
        public struct RightHandControlsActions
        {
            private @VRInputActions m_Wrapper;
            public RightHandControlsActions(@VRInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @RightGrip => m_Wrapper.m_RightHandControls_RightGrip;
            public InputAction @RightTrigger => m_Wrapper.m_RightHandControls_RightTrigger;
            public InputAction @RightPrimaryButton => m_Wrapper.m_RightHandControls_RightPrimaryButton;
            public InputAction @RightSecondaryButton => m_Wrapper.m_RightHandControls_RightSecondaryButton;
            public InputActionMap Get() { return m_Wrapper.m_RightHandControls; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(RightHandControlsActions set) { return set.Get(); }
            public void AddCallbacks(IRightHandControlsActions instance)
            {
                if (instance == null || m_Wrapper.m_RightHandControlsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_RightHandControlsActionsCallbackInterfaces.Add(instance);
                @RightGrip.started += instance.OnRightGrip;
                @RightGrip.performed += instance.OnRightGrip;
                @RightGrip.canceled += instance.OnRightGrip;
                @RightTrigger.started += instance.OnRightTrigger;
                @RightTrigger.performed += instance.OnRightTrigger;
                @RightTrigger.canceled += instance.OnRightTrigger;
                @RightPrimaryButton.started += instance.OnRightPrimaryButton;
                @RightPrimaryButton.performed += instance.OnRightPrimaryButton;
                @RightPrimaryButton.canceled += instance.OnRightPrimaryButton;
                @RightSecondaryButton.started += instance.OnRightSecondaryButton;
                @RightSecondaryButton.performed += instance.OnRightSecondaryButton;
                @RightSecondaryButton.canceled += instance.OnRightSecondaryButton;
            }

            private void UnregisterCallbacks(IRightHandControlsActions instance)
            {
                @RightGrip.started -= instance.OnRightGrip;
                @RightGrip.performed -= instance.OnRightGrip;
                @RightGrip.canceled -= instance.OnRightGrip;
                @RightTrigger.started -= instance.OnRightTrigger;
                @RightTrigger.performed -= instance.OnRightTrigger;
                @RightTrigger.canceled -= instance.OnRightTrigger;
                @RightPrimaryButton.started -= instance.OnRightPrimaryButton;
                @RightPrimaryButton.performed -= instance.OnRightPrimaryButton;
                @RightPrimaryButton.canceled -= instance.OnRightPrimaryButton;
                @RightSecondaryButton.started -= instance.OnRightSecondaryButton;
                @RightSecondaryButton.performed -= instance.OnRightSecondaryButton;
                @RightSecondaryButton.canceled -= instance.OnRightSecondaryButton;
            }

            public void RemoveCallbacks(IRightHandControlsActions instance)
            {
                if (m_Wrapper.m_RightHandControlsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IRightHandControlsActions instance)
            {
                foreach (var item in m_Wrapper.m_RightHandControlsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_RightHandControlsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public RightHandControlsActions @RightHandControls => new RightHandControlsActions(this);
        public interface ILeftHandControlsActions
        {
            void OnLeftGrip(InputAction.CallbackContext context);
            void OnLeftTrigger(InputAction.CallbackContext context);
            void OnLeftPrimaryButton(InputAction.CallbackContext context);
            void OnLeftSecondaryButton(InputAction.CallbackContext context);
        }
        public interface IRightHandControlsActions
        {
            void OnRightGrip(InputAction.CallbackContext context);
            void OnRightTrigger(InputAction.CallbackContext context);
            void OnRightPrimaryButton(InputAction.CallbackContext context);
            void OnRightSecondaryButton(InputAction.CallbackContext context);
        }
    }
}
